name: CI

on:
  push:
    branches: [ main, dep-inclusions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build